spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:&{PGPORT}/${PFDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create